name: Bun benchmark with bun install and node installed

on:
  - push
  - workflow_dispatch

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: setup bun
        uses: oven-sh/setup-bun@v1
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
      - name: Install dependencies
        run: bun install
      - name: Run small benchmark
        run: bun run benchmark:small:bun
      - name: Run medium benchmark
        run: bun run benchmark:medium:bun
      - name: Run large benchmark
        run: bun run benchmark:large:bun
      - name: Run nested benchmark
        run: bun run benchmark:nested:bun
      
