name: Node NX benchmark

on:
  - push
  - workflow_dispatch

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Install dependencies
        run: pnpm install
      - name: Run small benchmark
        run: pnpm benchmark:small:node
      - name: Run medium benchmark
        run: pnpm benchmark:medium:node
      - name: Run large benchmark
        run: pnpm benchmark:large:node
      - name: Run nested benchmark
        run: pnpm benchmark:nested:node
      
