name: Node benchmark with Bun Install

on:
  - push
  - workflow_dispatch

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: setup bun
        uses: oven-sh/setup-bun@v1
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
      - name: Install dependencies
        run: bun install
      - name: Run small benchmark
        run: pnpm benchmark:small:node
      - name: Run medium benchmark
        run: pnpm benchmark:medium:node
      - name: Run large benchmark
        run: pnpm benchmark:large:node
      - name: Run nested benchmark
        run: pnpm benchmark:nested:node
      
