name: Benchmark both

on:
  - push
  - workflow_dispatch

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: setup bun
        uses: oven-sh/setup-bun@v1
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
      - name: Install dependencies
        run: bun install

      - name: Run small benchmark - bun
        run: bun run benchmark:small:bun
      - name: Run small benchmark - node
        run: pnpm benchmark:small:node
    
      - name: Run medium benchmark -bun
        run: bun run benchmark:medium:bun
      - name: Run medium benchmark - node
        run: pnpm benchmark:medium:node

      - name: Run large benchmark - bun
        run: bun run benchmark:large:bun
      - name: Run large benchmark - node
        run: pnpm benchmark:large:node
      
      - name: Run nested benchmark - bun
        run: bun run benchmark:nested:bun
      - name: Run nested benchmark - node
        run: pnpm benchmark:nested:node
      
